### ISSUE TITLE
Force overwriting the symlink to the installed binary did not work

### ISSUE THREAD

**Issue by shenxianpeng** [cpp-linter/clang-tools-pip#20]
When the specific version (v12) of clang-tools was installed, trying to force overwriting the symlink to the installed library did not work.

```bash
ubuntu@CN-L:~/clang-tools-pip$ clang-format --version
clang-format version 7.1.0 (tags/RELEASE_710/final)

ubuntu@CN-L:~/clang-tools-pip$ clang-tools -i 12 -f
clang-format-12 already installed
clang-tidy-12 already installed

ubuntu@CN-L:~/clang-tools-pip$ clang-format --version
clang-format version 7.1.0 (tags/RELEASE_710/final)
```

Root cause: here return the false directly, also need to check `overwrite: bool`

https://github.com/cpp-linter/clang-tools-pip/blob/a4f8c90f8abdab261bb58451e0200bfb1bcba06d/clang_tools/install.py#L65

**Comment by shenxianpeng** [comment]
In the following case, when the clang-tools were installed with the apt-get install (Ubuntu), the target link is wrong.

Expect targe path is: `/home/ubuntu/.local/bin/clang-format-10`

https://github.com/cpp-linter/clang-tools-pip/blob/a4f8c90f8abdab261bb58451e0200bfb1bcba06d/clang_tools/install.py#L127

Actual path: `/usr/bin/clang-format-10`

```bash
(myenv) ubuntu@CN-L:~/clang-tools-pip$ which clang-format-10
/usr/bin/clang-format-10
(myenv) ubuntu@CN-L:~/clang-tools-pip$ clang-tools -i 10
clang-format-10 already installed
clang-tidy-10 already installed
```

**Comment by 2bndy5** [comment]
I'm not sure I understand. Did you want to create a symlink to the already installed binary?

**Comment by 2bndy5** [comment]
This kind of leads into "how to manage installed binaries?" I've been desiring a way to uninstall a binary for quicker testing purposes.

**Comment by shenxianpeng** [comment]
> Did you want to create a symlink to the already installed binary?

Yes

**Comment by 2bndy5** [comment]
The problem is that `is_installed()` does not check only the target's install path. It checks if the executable's name is able to be called. This means that when you `clang-tools -i 12`, ➡️ `is_installed()` ➡️ `subprocess.run(["clang-tidy-12", "--version"])`

Let's say there's nothing in the install path "~/.clang-tools" but you have clang-tidy-12 installed from `apt`
```
(env) brendan@B-DESKTOP:~$ sudo apt list clang-tidy-12
Listing... Done
clang-tidy-12/focal-updates,focal-security,now 1:12.0.0-3ubuntu1~20.04.5 amd64 [installed]
(env) brendan@B-DESKTOP:~$ ls ~/clang-tools/
<nothing to output>
```
Now when I go to install v12 (using our pkg) in a specific directory (`~/clang-tools`), it will detect the binary installed via `apt`, and it not be aware where the binary was installed:
(env) brendan@B-DESKTOP:~$ clang-tools -i 12 -d ~/clang-tools
/home/brendan/clang-tools directory is not in your environment variable PATH.
clang-format-12 already installed
clang-tidy-12 already installed
```
As you can see, creating a symlink in this situation is doomed because the binary was not downloaded and installed with our tool. It was instead installed using `apt`. The install path provided (via`-d`) is not the only path that our pkg checks when it looks to see if the binaries are installed.

**Comment by 2bndy5** [comment]
To find the binary installed via `apt`, we could use `which clang-*-<version>`, but this is Linux specific. In Windows, this is equivalent to `where` in DOS prompt or `Get-Command` in PowerShell.

However, I think you're only concerned with the binaries that we're installing with this pkg. In that case I think the real solution to this issue is:
```diff
--- a/clang_tools/install.py
+++ b/clang_tools/install.py
@@ -59,8 +59,7 @@ def clang_tools_binary_url(

 def install_tool(tool_name: str, version: str, directory: str) -> bool:
     """An abstract function that can install either clang-tidy or clang-format."""
-    if is_installed(tool_name, version):
-        # TODO should probably skip this if `directory` is not in the PATH env var.
+    if Path(directory, f"{tool_name}-{version}{suffix}").exists():
         print(f"{tool_name}-{version}", "already installed")
         return False
     bin_url = clang_tools_binary_url(tool_name, version)
@@ -162,5 +161,6 @@ def install_clang_tools(version: str, directory: str, overwrite: bool) -> None:
             f"directory is not in your environment variable PATH.{RESET_COLOR}",
         )
     for tool_name in ("clang-format", "clang-tidy"):
-        if install_tool(tool_name, version, install_dir):
+        target_downloaded = install_tool(tool_name, version, install_dir)
+        if target_downloaded or (not target_downloaded and overwrite):
             create_sym_link(tool_name, version, install_dir, overwrite)
```

But this will ignore anything that's already in the PATH env var. So, again, I think this issue is leading to "How to manage the installed binaries?"

**Comment by 2bndy5** [comment]
We should probably start using the SHA256 checksum provided with the binaries' releases to make sure the latest build of the version is installed.

**Comment by shenxianpeng** [comment]
Yes, that is another problem I mentioned here https://github.com/cpp-linter/clang-tools-pip/issues/23. For this issue is user pass `-f` but it doesn't work.

**Comment by 2bndy5** [comment]
So, just to clear things up for me:

Do you want to be able to create a symlink to any installed binary that gets invoked in `is_installed()`?

Or do you want to only create a symlink to the binaries that this pkg installs?

**Comment by shenxianpeng** [comment]
To be straightforward I want to create a symlink to the binaries that this pkg installs.

**Comment by 2bndy5** [comment]
Thank you. I can now work within those parameters.

**Comment by shenxianpeng** [comment]
I updated it after your review, please feel free to make changes.
